name: Call workflows

on:
    push:
      branches: ["main" ]
    pull_request:
      branches: ["main"]

jobs:
  snyk:
    uses: MoniSwon/devops-cours-faille/.github/workflows/snyk-security.yml@main

  Deploy-Preview:
    uses: MoniSwon/devops-cours-faille/.github/workflows/preview.yml@main
    needs: snyk
    