name: Call workflows

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
    push:
      branches: ["main" ]
    pull_request:
      branches: ["main"]

jobs:
  snyk:
    uses: MoniSwon/devops-cours-faille/.github/workflows/snyk-security.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  Deploy-Preview:
    uses: MoniSwon/devops-cours-faille/.github/workflows/preview.yml@main
    needs: snyk
    secrets:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    